name: component_set1
description: A new Flutter package project.
version: 0.0.1
author: "Nandang, Renoldi"
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  overlay_support: ^0.1.0
  flutter_svg: ^0.14.0
  reorderables: ^0.2.9
  component_icons:
    git:
      url: https://github.com/Renoldi/component_icon.git
      
  groovin_widgets:
    git:
      url: https://github.com/nandanghermawan21/GroovinWidgets.git
  flutter_google_places:
    git:
      url: https://github.com/nandanghermawan21/flutter_google_places.git
  google_maps_flutter: ^0.5.11+1
  location: ^2.3.5
  geolocator: ^5.1.1
  datetime_picker_formfield: ^0.1.8

  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf

    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
