name: component_set1
description: A new Flutter package project.
version: 0.0.1
author: "Nandang, Renoldi"
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # overlay_support: ^0.1.0
  overlay_support:
    git:
      url: https://github.com/boyan01/overlay_support.git

  # flutter_svg: ^0.13.0+2
  flutter_svg:
    git:
      url: https://github.com/dnfield/flutter_svg.git
  
  #reorderables: ^0.2.9
  reorderables:
    git:
      url: https://github.com/hanshengchiu/reorderables.git

  component_icons:
    git:
      url: https://github.com/Renoldi/component_icon.git
      
  groovin_widgets:
    git:
      url: https://github.com/nandanghermawan21/GroovinWidgets.git
  flutter_google_places:
    git:
      url: https://github.com/nandanghermawan21/flutter_google_places.git
  # google_maps_flutter: ^0.5.11+1
  google_maps_flutter:
    git:
      url: git://github.com/flutter/plugins.git
      path: packages/google_maps_flutter

  location: ^2.3.5
  geolocator: ^4.0.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf

    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
